### ISSUE TITLE
readme.md의 빌드 스크립트

### ISSUE THREAD

**Issue by kyeongrok3view** [Areum120/shopping_order_rpa#1]
pyinstall -w -F main.py 로 되어야 하는것 같아요

**Comment by Areum120** [comment]
전 요걸로 빌드했는데요 pyinstaller --onefile --noconsole classi\excel_clsfn.py

**Comment by Areum120** [comment]
pyinstall로 했는데 안되고 pyinstaller --onefile --noconsole excel_clsfn.py 이 명령어로 빌드함
