### ISSUE TITLE
빌드 후 실행시 Error

### ISSUE THREAD

**Issue by kyeongrok3view** [Areum120/shopping_order_rpa#2]
pyinstall -w -F main.py 로 빌드 후 실행하니 다음과 같이 에러 메세지가 발생 하였습니다.

<img width="753" alt="image" src="https://github.com/user-attachments/assets/8d16e022-bd57-45b7-9b36-7bacf19b196c">

**Comment by Areum120** [comment]
main.py가 아닌 excel_clsfn.py로 빌드함 됩니다
