### ISSUE TITLE
파일 전송시 용량 질문 300메가 넘는데 맞을까요?

### ISSUE THREAD

**Issue by kyeongrok3view** [Areum120/shopping_order_rpa#3]
300메가나 되네요. gmail은 30메가인가 넘으면 구글드라이브 통해서 보내게 되어 있구 다운로드도 오래 걸리네요ㅜ

<img width="386" alt="image" src="https://github.com/user-attachments/assets/8ae24393-2998-4b06-a5d9-87137cdf859e">

**Comment by Areum120** [comment]
불필요한 패키지 빼고 가시 빌드해야 될거 같아요
