### ISSUE TITLE
폴더생성 디폴트값

### ISSUE THREAD

**Issue by kyeongrok3view** [Areum120/shopping_order_rpa#5]
1. 경로 기본은 바탕화면으로 하면 좋을 것 같네요
2.  폴더 이름은 '셜록 생성 파일' 등 기본값을 주세요

**Comment by Areum120** [comment]
프로그램 실행시 자동으로 바탕화면 경로,폴더 설정 및 생성, 경로 설정하지 않아도 폴더 생성 버튼 클릭하면 생성됨
